INSERT INTO FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES (2, 'TEST', 'DESCRIPTION', '2022-08-10', 120, 1);
INSERT INTO FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES (3, 'TEST 2', 'DESCRIPTION', '2022-08-10', 120, 1);

INSERT INTO USERS (USER_ID, EMAIL, LOGIN, NAME, BIRTHDAY_DATE) VALUES (3, 'test@mail.com', 'test', 'Test Joe', '1989-08-10');

INSERT INTO LIKES (USER_ID, FILM_ID) VALUES (3, 2);